# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MRI-UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 600)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/DUET.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 30, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 170, 171, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("/DUET.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.buttonTrain = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTrain.setGeometry(QtCore.QRect(270, 130, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buttonTrain.setFont(font)
        self.buttonTrain.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.buttonTrain.setFlat(False)
        self.buttonTrain.setObjectName("buttonTrain")
        self.buttonTest = QtWidgets.QPushButton(self.centralwidget)
        self.buttonTest.setGeometry(QtCore.QRect(270, 220, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buttonTest.setFont(font)
        self.buttonTest.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.buttonTest.setFlat(False)
        self.buttonTest.setObjectName("buttonTest")
        self.buttonEval = QtWidgets.QPushButton(self.centralwidget)
        self.buttonEval.setGeometry(QtCore.QRect(270, 310, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.buttonEval.setFont(font)
        self.buttonEval.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.buttonEval.setFlat(False)
        self.buttonEval.setObjectName("buttonEval")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 430, 421, 51))
        self.label_3.setStyleSheet("alternate-background-color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 500, 501, 51))
        self.label_4.setStyleSheet("alternate-background-color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MRI Reconstruction"))
        self.label.setText(_translate("MainWindow", "MRI Reconstruction Using CNN"))
        self.buttonTrain.setText(_translate("MainWindow", "Train Network"))
        self.buttonTest.setText(_translate("MainWindow", "Test Network"))
        self.buttonEval.setText(_translate("MainWindow", "Reconstruct MRI"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#5500ff;\">Submitted To: Dr. Rafiqul Islam, Associate Professor, CSE, DUET</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#5500ff;\">Submitted By: Omar Faruque, Std. Id: 18204020, MSc. Engg., CSE, DUET</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
